


















.build_ano/atmegang/arduino/wiring.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring.c
	@echo arduino/wiring.c
	@mkdir -p .build_ano/atmegang/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega8 -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/standard -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -I/usr/share/arduino/hardware/arduino/avr/libraries/EEPROM   -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring.c
include .build_ano/atmegang/arduino/wiring.d

.build_ano/atmegang/arduino/WInterrupts.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/WInterrupts.c
	@echo arduino/WInterrupts.c
	@mkdir -p .build_ano/atmegang/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega8 -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/standard -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -I/usr/share/arduino/hardware/arduino/avr/libraries/EEPROM   -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/WInterrupts.c
include .build_ano/atmegang/arduino/WInterrupts.d

.build_ano/atmegang/arduino/wiring_pulse.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_pulse.c
	@echo arduino/wiring_pulse.c
	@mkdir -p .build_ano/atmegang/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega8 -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/standard -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -I/usr/share/arduino/hardware/arduino/avr/libraries/EEPROM   -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_pulse.c
include .build_ano/atmegang/arduino/wiring_pulse.d

.build_ano/atmegang/arduino/wiring_shift.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_shift.c
	@echo arduino/wiring_shift.c
	@mkdir -p .build_ano/atmegang/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega8 -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/standard -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -I/usr/share/arduino/hardware/arduino/avr/libraries/EEPROM   -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_shift.c
include .build_ano/atmegang/arduino/wiring_shift.d

.build_ano/atmegang/arduino/hooks.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/hooks.c
	@echo arduino/hooks.c
	@mkdir -p .build_ano/atmegang/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega8 -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/standard -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -I/usr/share/arduino/hardware/arduino/avr/libraries/EEPROM   -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/hooks.c
include .build_ano/atmegang/arduino/hooks.d

.build_ano/atmegang/arduino/wiring_digital.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_digital.c
	@echo arduino/wiring_digital.c
	@mkdir -p .build_ano/atmegang/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega8 -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/standard -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -I/usr/share/arduino/hardware/arduino/avr/libraries/EEPROM   -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_digital.c
include .build_ano/atmegang/arduino/wiring_digital.d

.build_ano/atmegang/arduino/wiring_analog.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_analog.c
	@echo arduino/wiring_analog.c
	@mkdir -p .build_ano/atmegang/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega8 -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/standard -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -I/usr/share/arduino/hardware/arduino/avr/libraries/EEPROM   -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/wiring_analog.c
include .build_ano/atmegang/arduino/wiring_analog.d






.build_ano/atmegang/arduino/HardwareSerial2.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial2.cpp
	@echo arduino/HardwareSerial2.cpp
	@mkdir -p .build_ano/atmegang/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega8 -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/standard -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -I/usr/share/arduino/hardware/arduino/avr/libraries/EEPROM -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial2.cpp
include .build_ano/atmegang/arduino/HardwareSerial2.d

.build_ano/atmegang/arduino/HardwareSerial1.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial1.cpp
	@echo arduino/HardwareSerial1.cpp
	@mkdir -p .build_ano/atmegang/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega8 -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/standard -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -I/usr/share/arduino/hardware/arduino/avr/libraries/EEPROM -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial1.cpp
include .build_ano/atmegang/arduino/HardwareSerial1.d

.build_ano/atmegang/arduino/WString.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/WString.cpp
	@echo arduino/WString.cpp
	@mkdir -p .build_ano/atmegang/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega8 -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/standard -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -I/usr/share/arduino/hardware/arduino/avr/libraries/EEPROM -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/WString.cpp
include .build_ano/atmegang/arduino/WString.d

.build_ano/atmegang/arduino/HID.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/HID.cpp
	@echo arduino/HID.cpp
	@mkdir -p .build_ano/atmegang/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega8 -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/standard -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -I/usr/share/arduino/hardware/arduino/avr/libraries/EEPROM -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/HID.cpp
include .build_ano/atmegang/arduino/HID.d

.build_ano/atmegang/arduino/HardwareSerial3.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial3.cpp
	@echo arduino/HardwareSerial3.cpp
	@mkdir -p .build_ano/atmegang/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega8 -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/standard -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -I/usr/share/arduino/hardware/arduino/avr/libraries/EEPROM -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial3.cpp
include .build_ano/atmegang/arduino/HardwareSerial3.d

.build_ano/atmegang/arduino/main.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/main.cpp
	@echo arduino/main.cpp
	@mkdir -p .build_ano/atmegang/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega8 -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/standard -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -I/usr/share/arduino/hardware/arduino/avr/libraries/EEPROM -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/main.cpp
include .build_ano/atmegang/arduino/main.d

.build_ano/atmegang/arduino/HardwareSerial0.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial0.cpp
	@echo arduino/HardwareSerial0.cpp
	@mkdir -p .build_ano/atmegang/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega8 -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/standard -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -I/usr/share/arduino/hardware/arduino/avr/libraries/EEPROM -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial0.cpp
include .build_ano/atmegang/arduino/HardwareSerial0.d

.build_ano/atmegang/arduino/CDC.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/CDC.cpp
	@echo arduino/CDC.cpp
	@mkdir -p .build_ano/atmegang/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega8 -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/standard -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -I/usr/share/arduino/hardware/arduino/avr/libraries/EEPROM -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/CDC.cpp
include .build_ano/atmegang/arduino/CDC.d

.build_ano/atmegang/arduino/Print.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/Print.cpp
	@echo arduino/Print.cpp
	@mkdir -p .build_ano/atmegang/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega8 -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/standard -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -I/usr/share/arduino/hardware/arduino/avr/libraries/EEPROM -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/Print.cpp
include .build_ano/atmegang/arduino/Print.d

.build_ano/atmegang/arduino/Stream.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/Stream.cpp
	@echo arduino/Stream.cpp
	@mkdir -p .build_ano/atmegang/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega8 -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/standard -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -I/usr/share/arduino/hardware/arduino/avr/libraries/EEPROM -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/Stream.cpp
include .build_ano/atmegang/arduino/Stream.d

.build_ano/atmegang/arduino/abi.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/abi.cpp
	@echo arduino/abi.cpp
	@mkdir -p .build_ano/atmegang/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega8 -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/standard -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -I/usr/share/arduino/hardware/arduino/avr/libraries/EEPROM -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/abi.cpp
include .build_ano/atmegang/arduino/abi.d

.build_ano/atmegang/arduino/WMath.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/WMath.cpp
	@echo arduino/WMath.cpp
	@mkdir -p .build_ano/atmegang/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega8 -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/standard -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -I/usr/share/arduino/hardware/arduino/avr/libraries/EEPROM -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/WMath.cpp
include .build_ano/atmegang/arduino/WMath.d

.build_ano/atmegang/arduino/HardwareSerial.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial.cpp
	@echo arduino/HardwareSerial.cpp
	@mkdir -p .build_ano/atmegang/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega8 -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/standard -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -I/usr/share/arduino/hardware/arduino/avr/libraries/EEPROM -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/HardwareSerial.cpp
include .build_ano/atmegang/arduino/HardwareSerial.d

.build_ano/atmegang/arduino/Tone.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/Tone.cpp
	@echo arduino/Tone.cpp
	@mkdir -p .build_ano/atmegang/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega8 -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/standard -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -I/usr/share/arduino/hardware/arduino/avr/libraries/EEPROM -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/Tone.cpp
include .build_ano/atmegang/arduino/Tone.d

.build_ano/atmegang/arduino/IPAddress.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/IPAddress.cpp
	@echo arduino/IPAddress.cpp
	@mkdir -p .build_ano/atmegang/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega8 -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/standard -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -I/usr/share/arduino/hardware/arduino/avr/libraries/EEPROM -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/IPAddress.cpp
include .build_ano/atmegang/arduino/IPAddress.d

.build_ano/atmegang/arduino/USBCore.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/USBCore.cpp
	@echo arduino/USBCore.cpp
	@mkdir -p .build_ano/atmegang/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega8 -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/standard -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -I/usr/share/arduino/hardware/arduino/avr/libraries/EEPROM -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/USBCore.cpp
include .build_ano/atmegang/arduino/USBCore.d

.build_ano/atmegang/arduino/new.o : /usr/share/arduino/hardware/arduino/avr/cores/arduino/new.cpp
	@echo arduino/new.cpp
	@mkdir -p .build_ano/atmegang/arduino
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega8 -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/standard -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -I/usr/share/arduino/hardware/arduino/avr/libraries/EEPROM -fno-exceptions  -o $@ -c /usr/share/arduino/hardware/arduino/avr/cores/arduino/new.cpp
include .build_ano/atmegang/arduino/new.d



.build_ano/atmegang/arduino/libarduino.a : .build_ano/atmegang/arduino/wiring.o .build_ano/atmegang/arduino/WInterrupts.o .build_ano/atmegang/arduino/wiring_pulse.o .build_ano/atmegang/arduino/wiring_shift.o .build_ano/atmegang/arduino/hooks.o .build_ano/atmegang/arduino/wiring_digital.o .build_ano/atmegang/arduino/wiring_analog.o .build_ano/atmegang/arduino/HardwareSerial2.o .build_ano/atmegang/arduino/HardwareSerial1.o .build_ano/atmegang/arduino/WString.o .build_ano/atmegang/arduino/HID.o .build_ano/atmegang/arduino/HardwareSerial3.o .build_ano/atmegang/arduino/main.o .build_ano/atmegang/arduino/HardwareSerial0.o .build_ano/atmegang/arduino/CDC.o .build_ano/atmegang/arduino/Print.o .build_ano/atmegang/arduino/Stream.o .build_ano/atmegang/arduino/abi.o .build_ano/atmegang/arduino/WMath.o .build_ano/atmegang/arduino/HardwareSerial.o .build_ano/atmegang/arduino/Tone.o .build_ano/atmegang/arduino/IPAddress.o .build_ano/atmegang/arduino/USBCore.o .build_ano/atmegang/arduino/new.o
	@echo Linking libarduino.a
	@/usr/share/arduino/hardware/tools/avr/bin/avr-ar rcs $@ $^














.build_ano/atmegang/EEPROM/libEEPROM.a : 
	@echo Linking libEEPROM.a
	@/usr/share/arduino/hardware/tools/avr/bin/avr-ar rcs $@ $^















.build_ano/atmegang/src/main.o : src/main.cpp
	@echo src/main.cpp
	@mkdir -p .build_ano/atmegang/src
	@/usr/share/arduino/hardware/tools/avr/bin/avr-g++ -mmcu=atmega8 -DF_CPU=16000000L -DARDUINO=165 -DARDUINO_ARCH_AVR -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -ffunction-sections -fdata-sections -g -Os -w -I/usr/share/arduino/hardware/arduino/avr/variants/standard -I/usr/share/arduino/hardware/arduino/avr/cores/arduino -I/usr/share/arduino/hardware/arduino/avr/libraries/EEPROM -fno-exceptions  -o $@ -c src/main.cpp
include .build_ano/atmegang/src/main.d







.build_ano/atmegang/firmware.elf : .build_ano/atmegang/src/main.o .build_ano/atmegang/arduino/libarduino.a .build_ano/atmegang/EEPROM/libEEPROM.a
	@echo Linking firmware.elf
	@/usr/share/arduino/hardware/tools/avr/bin/avr-gcc -mmcu=atmega8 -Wl,-Os -Wl,--gc-sections -o $@ $^ -lm


.build_ano/atmegang/firmware.hex : .build_ano/atmegang/firmware.elf
	@echo Converting to firmware.hex
	@/usr/share/arduino/hardware/tools/avr/bin/avr-objcopy -O ihex -R .eeprom $^ $@

include .build_ano/atmegang/src/dependencies.d .build_ano/atmegang/arduino/dependencies.d .build_ano/atmegang/EEPROM/dependencies.d

all : .build_ano/atmegang/firmware.hex
	@true

